### PR TITLE
Added logging feature

### PR DESCRIPTION
**Pull request by yatsenko-ihor**
We implemented logging feature accordingly to your requirements:
1) Please leverage Java's built-in Logger class. We aim to be compatible with Java 6, so please do not use any features that are not present in Java 6.
2) We attempt to keep our Libraries as idiomatic as possible across different languages. We already have an implementation for logging in our Ruby client library. Please follow the implementation in configuration.rb and http.rb as closely as possible.

Please review it. Thank you.

### CODE REVIEW

**Comment by omgrr** [comment]
Thanks @yatsenko-ihor this looks great! We're going to start adding some tests around it and will let you know if we have any questions or news.

**Comment by vsinjavin** [comment]
Hi @omgrr, is there any ETA when it can be merged to the master? It's really important for us to have this changes for our project.

Thanks in advance.

**Comment by omgrr** [comment]
I can't provide an ETA, but I have started working on this. I will keep you updated, thanks!

**Comment by vsinjavin** [comment]
Hi @omgrr, are there any news?

Thanks

**Comment by omgrr** [comment]
Hey @vsinjavin we're still working on it. There are still a couple of more tests that we need to add before we merge this.

**Comment by omgrr** [comment]
This has been added in 2.57.0. Thanks again for your contribution and patience!

**Pull request closed without merging**
